---
- name: Harden rke2 
  hosts: all
  gather_facts: no
  become: true
  become_method: sudo
  become_exe: /usr/bin/sudo
  
  tasks:
  - name: remove old cis profile in /etc/rancher/rke2/config.yaml
    lineinfile:
      path: /etc/rancher/rke2/config.yaml
      line: 'profile: "cis-1.5"'
      state: absent
    when: inventory_hostname in rancher_all_api or
          inventory_hostname in rancher_all_mcm or
          inventory_hostname in rancher_workers
  
  - name: Add cis-1.6 hardening to config.yaml
    lineinfile:
      path: /etc/rancher/rke2/config.yaml
      line: "{{ item }}"
      state: present
    with_items:
      - 'profile: "cis-1.6"'
    when: inventory_hostname in rancher_all_api or
          inventory_hostname in rancher_all_mcm or
          inventory_hostname in rancher_workers
 
  - name: Add additional cis-1.6 hardening to config.yaml
    lineinfile:
      path: /etc/rancher/rke2/config.yaml
      line: "{{ item }}"
      state: present
    with_items:
      - 'write-kubeconfig-mode: "0644"'
      - 'selinux: true'
    when: inventory_hostname in rancher_api0 or
          inventory_hostname in rancher_mcm0
 
  - name: Add cis-1.6 apiserver hardening to config.yaml on rke2 controlplanes
    lineinfile:
      path: /etc/rancher/rke2/config.yaml
      line: "{{ item }}"
      state: present
    with_items:
      - 'kube-apiserver-arg:'
      - '  - "service-account-lookup=true"'
      - '  - "tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"'
      - '  - "enable-admission-plugins=NodeRestriction,PodSecurityPolicy,AlwaysPullImages"'
    when: inventory_hostname in rancher_all_api or
          inventory_hostname in rancher_all_mcm 
 
  - name: Add etcd group
    group:
      name: etcd
      state: present
    when: inventory_hostname in rancher_all_api or
          inventory_hostname in rancher_all_mcm or
          inventory_hostname in rancher_workers
          
  - name: Add etcd user
    user:
      name: etcd
      group: etcd
      state: present
      shell: /sbin/nologin
      comment: "etcd user"
    when: inventory_hostname in rancher_all_api or
          inventory_hostname in rancher_all_mcm or
          inventory_hostname in rancher_workers

  - name: Copy rke2-cis-sysctl.conf to sysctl.d
    copy:
      src: /usr/local/share/rke2/rke2-cis-sysctl.conf
      dest: /etc/sysctl.d/60-rke2-cis.conf
      remote_src: yes
    when: inventory_hostname in rancher_all_api or
          inventory_hostname in rancher_all_mcm or
          inventory_hostname in rancher_workers

  - name: Remove system-default-registry declaration in config.yaml for rke2 1.20.X and greater
    lineinfile:
      path: "/etc/rancher/rke2/config.yaml"
      regexp: "^system-default-registry"
      state: absent
    when: rke2_version is version('1.20', '>=') and
          (inventory_hostname in rancher_all_api or
          inventory_hostname in rancher_all_mcm or
          inventory_hostname in rancher_workers)

  - name: Modify registries.yaml for 1.20.X and greater
    replace:
      path: "/etc/rancher/rke2/registries.yaml"
      regexp: "^#replace"
      replace: ""
    when: rke2_version is version('1.20', '>=') and
          (inventory_hostname in rancher_all_api or
          inventory_hostname in rancher_all_mcm or
          inventory_hostname in rancher_workers)

