---
- name: Install rke2 first_node
  hosts: all
  gather_facts: no
  become: true
  become_method: sudo
  become_exe: /usr/bin/sudo
  
  tasks:
  - name: Determine if mcm
    set_fact:
      stublette: mcm
    when: inventory_hostname in rancher_all_mcm

  - name: Determine if api
    set_fact:
      stublette: api
    when: inventory_hostname in rancher_all_api

  - name: Determine if worker
    set_fact:
      stublette: worker
    when: inventory_hostname in rancher_workers

  - name: Determine if other
    set_fact:
      stublette: other
    when: inventory_hostname not in rancher_all_api and
          inventory_hostname not in rancher_all_mcm and
          inventory_hostname not in rancher_workers

  - name: Populate config.yaml
    template:
      src: "templates/etc/rancher/rke2/config.yaml.{{ stublette }}-first"
      dest: "/etc/rancher/rke2/config.yaml"

  - name: Remove system-default-registry declaration in config.yaml for rke2 1.20.X and greater
    lineinfile:
      path: "/etc/rancher/rke2/config.yaml"
      regexp: "^system-default-registry"
      state: absent
    when: rke2_version is version('1.20', '>=')

  - name: Add etcd group
    group:
      name: etcd
      state: present
    when: inventory_hostname in rancher_all_api or
          inventory_hostname in rancher_all_mcm or
          inventory_hostname in rancher_workers
          
  - name: Add etcd user
    user:
      name: etcd
      group: etcd
      state: present
      shell: /sbin/nologin
      comment: "etcd user"
    when: inventory_hostname in rancher_all_api or
          inventory_hostname in rancher_all_mcm or
          inventory_hostname in rancher_workers

  - name: Modify registries.yaml for 1.20.X and greater
    replace:
      path: "/etc/rancher/rke2/registries.yaml"
      regexp: "^#replace"
      replace: ""
    when: rke2_version is version('1.20', '>=') and
          (inventory_hostname in rancher_all_api or
          inventory_hostname in rancher_all_mcm or
          inventory_hostname in rancher_workers)

  - name: start rke2-server
    systemd:
      name: rke2-server
      enabled: yes
      state: started
      daemon_reload: yes

  - name: loop for status
    shell: 
      cmd: "/var/lib/rancher/rke2/bin/kubectl get nodes |grep {{ inventory_hostname }} |grep -v NotReady| grep Ready"
    register: first_node_up
    until: first_node_up.rc == 0
    retries: 20
    delay: 30

  - name: set fact for mcm token
    shell: 
      cmd: cat /var/lib/rancher/rke2/server/token
    register: rancher_mcm_first_token
    when: inventory_hostname in rancher_mcm0

  - name: set fact for api token
    shell: 
      cmd: cat /var/lib/rancher/rke2/server/token
    register: rancher_api_first_token
    when: inventory_hostname in rancher_api0

  - name: Copy rke2-cis-sysctl.conf to sysctl.d
    copy:
      src: /usr/local/share/rke2/rke2-cis-sysctl.conf
      dest: /etc/sysctl.d/60-rke2-cis.conf
      remote_src: yes
    when: inventory_hostname in rancher_all_api or
          inventory_hostname in rancher_all_mcm or
          inventory_hostname in rancher_workers
