---
- name: Install rke2 worker node
  hosts: all
  gather_facts: no
  become: true
  become_method: sudo
  become_exe: /usr/bin/sudo
  
  tasks:
  - name: Determine if worker
    set_fact:
      stublette: "api"

  - name: Set first node if api
    set_fact: 
      first_node: "{{ rancher_api0 }}"

  - name: set fact for api token
    shell:
      cmd: cat /var/lib/rancher/rke2/server/token
    register: rancher_api_first_token
    delegate_to: "{{ first_node }}"

  - name: set rke2_token
    set_fact:
      rke2_token: "{{ rancher_api_first_token.stdout }}"

  - name: Populate config.yaml
    template:
      src: "templates/etc/rancher/rke2/config.yaml.{{ stublette }}-worker"
      dest: "/etc/rancher/rke2/config.yaml"

  - name: Remove system-default-registry declaration in config.yaml for rke2 1.20.X and greater
    lineinfile:
      path: "/etc/rancher/rke2/config.yaml"
      regexp: "^system-default-registry"
      state: absent
    when: rke2_version is version('1.20', '>=')

  - name: Add etcd group
    group:
      name: etcd
      state: present
    when: inventory_hostname in rancher_all_api or
          inventory_hostname in rancher_workers
          
  - name: Add etcd user
    user:
      name: etcd
      group: etcd
      state: present
      shell: /sbin/nologin
      comment: "etcd user"
    when: inventory_hostname in rancher_all_api or
          inventory_hostname in rancher_workers

  - name: Modify registries.yaml for 1.20.X and greater
    replace:
      path: "/etc/rancher/rke2/registries.yaml"
      regexp: "^#replace"
      replace: ""
    when: rke2_version is version('1.20', '>=') and
          (inventory_hostname in rancher_all_api or
          inventory_hostname in rancher_workers)

  - name: start rke2-agent
    systemd:
      name: rke2-agent
      enabled: yes
      state: started
      daemon_reload: yes

  - name: Copy rke2-cis-sysctl.conf to sysctl.d
    copy:
      src: /usr/local/share/rke2/rke2-cis-sysctl.conf
      dest: /etc/sysctl.d/60-rke2-cis.conf
      remote_src: yes
    when: inventory_hostname in rancher_all_api or
          inventory_hostname in rancher_workers
