---
- name: Patch Rancher Cluster Nodes
  hosts: all
  gather_facts: no
  become: true
  become_method: sudo
  become_exe: /usr/bin/sudo
  serial: 1
  
  tasks:
  - name: get bundle ver
    include_tasks: get_bundlever_task.yaml

  - name: add company Repo for SLES
    template:
      src: "templates/etc/zypp/repos.d/{{ item }}"
      dest: "/etc/zypp/repos.d/{{ item }}"
      owner: root
      group: root
      mode: '0644'
    with_items: 
      - company_sles-15.2.repo
      - company_sles-15.3.repo

  - name: Patch
    zypper: 
      name: "*"
      state: latest
      update_cache: yes

  - name: Check if a reboot is needed on all SUSE/OpenSUSE based servers
    register: linux_reboot_required_file
    stat: path=/boot/do_purge_kernels get_md5=no

  - name: Reboot the server
    shell: 
      cmd: /sbin/shutdown -r +1 "Ansible directed shutdown"
    poll: 0
    when: linux_reboot_required_file.stat.exists

  - name: Wait for ssh to be available
    wait_for_connection: 
      delay: 90
      sleep: 20
    become: false
    when: linux_reboot_required_file.stat.exists

  - name: wait for several minutes to allow for node to come up
    wait_for:
      timeout: 180
    when: linux_reboot_required_file.stat.exists
