apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: company-gatekeeper
  namespace: fleet-default
spec:
  branch: prod
  insecureSkipTLSVerify: true
  paths:
  - ./rancher-gatekeeper-crd
  - ./rancher-gatekeeper
  - ./templates
  - ./constraints
  pollingInterval: 60s
  repo: https://github.company.com/itas/k8s-opa-constraints
  targets:
  - clusterSelector: {}
